### ISSUE TITLE
Provide Contentful setup

### ISSUE THREAD

**Issue by stefanjudis** [joshhebb/angularjs-contentful-starter#1]
Hey Josh! 👋🏻

This looks great! Love the look of the Apple Store. I've got one question (and disclaimer: I work for Contentful). Have you considered providing the content model to make the start easier for people?

[import](https://github.com/contentful/contentful-import) and [export](https://github.com/contentful/contentful-export) could be used and an import could run in `npm run init` to also set up a complete Contentful space. :)

Is this something you'd be interested in?
But anyways thanks for putting this on GitHub. 🎉

**Comment by joshhebb** [comment]
Ah that's a wicked idea @stefanjudis . I had no idea. I'm going to set that up immediately!

**Comment by joshhebb** [comment]
I've included this in v1.1.0 @stefanjudis . Thanks again for the suggestion. When you run the init script, your prompted for your space ID and tokens which gulp eventually builds into an angularjs constants file for the app. 

PS The export & import tools are great!
